from setuptools import setup

setup(
    name='ldap2mattermost',
    version='0,1',
    packages=['venv.lib.python3.5.site-packages.pip', 'venv.lib.python3.5.site-packages.pip.req', 'venv.lib.python3.5.site-packages.pip.vcs',
              'venv.lib.python3.5.site-packages.pip.utils', 'venv.lib.python3.5.site-packages.pip.compat', 'venv.lib.python3.5.site-packages.pip.models',
              'venv.lib.python3.5.site-packages.pip._vendor', 'venv.lib.python3.5.site-packages.pip._vendor.idna',
              'venv.lib.python3.5.site-packages.pip._vendor.certifi', 'venv.lib.python3.5.site-packages.pip._vendor.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.chardet.cli', 'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport', 'venv.lib.python3.5.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.util', 'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport', 'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname', 'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib', 'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters', 'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters', 'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile', 'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests', 'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol', 'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings', 'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations', 'venv.lib.python3.5.site-packages.ldap3',
              'venv.lib.python3.5.site-packages.ldap3.core', 'venv.lib.python3.5.site-packages.ldap3.utils', 'venv.lib.python3.5.site-packages.ldap3.extend',
              'venv.lib.python3.5.site-packages.ldap3.extend.novell', 'venv.lib.python3.5.site-packages.ldap3.extend.standard',
              'venv.lib.python3.5.site-packages.ldap3.extend.microsoft', 'venv.lib.python3.5.site-packages.ldap3.abstract',
              'venv.lib.python3.5.site-packages.ldap3.protocol', 'venv.lib.python3.5.site-packages.ldap3.protocol.sasl',
              'venv.lib.python3.5.site-packages.ldap3.protocol.schemas', 'venv.lib.python3.5.site-packages.ldap3.protocol.formatters',
              'venv.lib.python3.5.site-packages.ldap3.strategy', 'venv.lib.python3.5.site-packages.ldap3.operation', 'venv.lib.python3.5.site-packages.pyasn1',
              'venv.lib.python3.5.site-packages.pyasn1.type', 'venv.lib.python3.5.site-packages.pyasn1.codec',
              'venv.lib.python3.5.site-packages.pyasn1.codec.ber', 'venv.lib.python3.5.site-packages.pyasn1.codec.cer',
              'venv.lib.python3.5.site-packages.pyasn1.codec.der', 'venv.lib.python3.5.site-packages.pyasn1.codec.native',
              'venv.lib.python3.5.site-packages.pyasn1.compat'],
    url='',
    license='',
    author='Mark de Bruijn',
    author_email='m.debruijn@kopano.com',
    description='Bulk import users from LDAP to Mattermost'
)
